### ISSUE TITLE
Mail image system path incorrect

### ISSUE THREAD

**Issue by tkdrob** [moralmunky/Home-Assistant-Mail-And-Packages-Custom-Card#19]
**Describe the bug**
The image path sensor starts with /config/www. This should instead be /local. Not sure why, but lovelace doesn't seem to show image otherwise. 

**To Reproduce**
Use developer tools to change path. 

**Expected behavior**
Image should show using default sensor.

**Screenshots or Error**

**Hass environment (please complete the following information):**
- Type of install Supervised 2012.2.0b0
- OS Debian Buster

**Comment by moralmunky** [comment]
Where are you trying to use the path provided by that sensor?

**Comment by tkdrob** [comment]
The gif sensor option in the custom lovelace card. Replacing gif uuid with mail_today for file name and having path set to /local/mail_and_packages/mail_today.gif seems to work at the moment.

**Comment by moralmunky** [comment]
You should be using the sensor.mail_image_url not sensor.mail_image_system_path to supply the gif sensor option in the latest pre-release of the custom card that pairs with the most recent versions of the integration, <b34.

sensor.mail_image_system_path is used for setting up a local file cameras if you choose use a camera entity to display the image.

These sensors must be used because the default name is no longer mail_today.gif. It is a random image string for the image.

sensor.mail_image_url does require that you have the internal/external URL set in the system configuration.

**Comment by tkdrob** [comment]
Thanks. Its working now.
