### ISSUE TITLE
Mail GIF Not Working

### ISSUE THREAD

**Issue by mdframe** [moralmunky/Home-Assistant-Mail-And-Packages-Custom-Card#20]
I am unable to get the mail gif to work.  I can manually look and see the mail_today.gif file in /config/images/mail_and_packages/ however I do not get any images in the card.  Here is my card setup:

type: 'custom:mail-and-packages-card'
name: Mail Summary
updated: sensor.mail_usps_delivered
details: true
image: true
fedex_packages: sensor.mail_fedex_packages
ups_packages: sensor.mail_ups_packages
usps_packages: sensor.mail_usps_packages
amazon_packages: sensor.mail_amazon_packages
usps_mail: sensor.mail_usps_packages
camera_entity: camera.mail_usps
gif_sensor: sensor.mail_image_system_path
deliveries_message: sensor.mail_deliveries_message
packages_delivered: sensor.mail_usps_delivered
packages_in_transit: sensor.mail_ups_delivering

I will admit I may be causing the issue myself as I may not have created all the sensors correctly with my recent reinstall.

**Comment by moralmunky** [comment]
There are two ways to go about getting the image. 

The file name mail_today.gif is no longer used, it has been permanently changed to a random file name for security. You may see it until integration runs. Browser cache can be an issue. I can't say one is better than the other. For notification I prefer the gif since there isn't an extra set to push play to see the animation.

### Camera Entity
Set up a camera and have an automation update the path using the sensor.mail_image_system_path. I think this requires the new option 'allow external image use' is turned off. Current instructions in the [forum](https://community.home-assistant.io/t/mail-and-packages-custom-component-for-ups-fedex-and-usps/118081/1286?u=moralmunky).

The camera can be added to the custom card or added to a dashboard on its own.

### Gif file in the custom card
This requires the new option 'allow external image use' is turned off and you will use the sensor.mail_image_url for the GIF sensor.

**Comment by sphanley** [comment]
Hi @moralmunky - hoping you can help with this:

> ### Gif file in the custom card
> This requires the new option 'allow external image use' is turned off and you will use the sensor.mail_image_url for the GIF sensor.

On both 0.04 and 0.06, I'm seeing a version of the card configuration screen where rather than giving the option to pick a sensor to provide the GIF location, the GIF location field is just a textbox, and seems to only accept a static URL.

<img width="491" alt="Screen Shot 2021-03-13 at 11 21 52 AM" src="https://user-images.githubusercontent.com/1323769/111036666-58311980-83ee-11eb-91a5-0a3931fd7321.png">

Am I doing something wrong? Or should I open a new issue?

**Comment by sphanley** [comment]
Nevermind, it looks like it was just an issue with the cache not clearing properly after updating from 0.04 to 0.06. Looking good now!

**Comment by rjmcfadd** [comment]
I'm having the same issue. I've cleared my cache and reinstalled the mail & packages integration and card but it only shows a textbox for gif location. If I just type in 'sensor.mail_image_url' nothing happens. Any other suggestions?

**Comment by sphanley** [comment]
Strangely, what worked for me was loading it in another browser - e.g. it wasn't working in Chrome, then I loaded it in Safari, where it worked. Then when I went back to Chrome and cleared my cache one more time, it was rendering correctly. Maybe make sure you've installed 0.06 and then try that?

**Comment by rjmcfadd** [comment]
Maybe that's it. The latest version that is showing for me is 0.04. I can't figure out why that is though.

**Comment by sphanley** [comment]
In HACS, you've got to turn on "Show Beta Versions" (or something like that). 0.06 hasn't been released as stable yet.

**Comment by rjmcfadd** [comment]
Thanks, @sphanley! I had checked that but it didn't show the update until I restarted. 

Then I used the trick you said about opening it in Safari and clearing my cache one more time.
