### ISSUE TITLE
Feature Request: My Ideal Mail Card

### ISSUE THREAD

**Issue by julianrinaldi** [moralmunky/Home-Assistant-Mail-And-Packages-Custom-Card#27]
**Is your feature request related to a problem? Please describe.**
My ideal mail and packages card would have the layout and names be how it used to be:
<img width="687" alt="CleanShot 2021-03-23 at 08 18 24@2x" src="https://user-images.githubusercontent.com/492435/112145162-6af6db80-8bb0-11eb-982c-9635b1c576e3.png">
I like the Amazon sensor to be up there, and there's really no reason to keep repeating "packages".

It would allow the Amazon delivered sensor to be combined into the main delivered sensor. So if you have 3 Amazon packages delivered and 2 UPS deliveries delivered, the delivered sensor would show 5 instead of 2.

I would also love there to be a. combined mail/amazon camera so that if there was an Amazon delivery photo from that day, it would show in the same camera feed as the mail you're receiving.

I would also like to be able to remove the "Last Check" sensor from the card.

Just wanted to say thanks again for the integration/card. I've sent you a tip yesterday. This integration is actually the one that impresses people the most when they see my dashboard.

Sorry if you're already planning on working on many of these things.

**Comment by moralmunky** [comment]
The last time we evaluated Amazon, they are a retailer that happens to ship and not a shipper and still use external shipper and would double up the totals when this happens so they are kept separate.

Submit your image functionality as a request to the integration. I understand the want but not convinced it should be combined.

I'll take the last checked into consideration since all the sensors are pretty much becoming toggle switches it would make sense to toggle that too.
